In [4]:
# -*- coding: utf-8 -*-
"""
Created on 11/15/18

@author: arjun with edits by Dustin
"""

import pandas as pd
import numpy as np
import sqlite3 as sq
from math import sqrt
from scipy import stats, spatial
from scipy.sparse import csr_matrix


def import_standard_data(db_path):
    conn = sq.connect(db_path) #sqliteDB path goes in parantheses
    crsr = conn.cursor()

    df = pd.read_sql_query('''
                SELECT DISTINCT
                    customer_id,
                    product_id,
                    product_parent,
                    star_rating,
                    helpful_votes,
                    review_headline,
                    review_body,
                    product_category,
                    marketplace,
                    review_date,
                    verified_purchase
                FROM books
                WHERE star_rating IN (
                                    SELECT star_rating
                                    FROM books
                                    GROUP BY customer_id
                                    HAVING COUNT(star_rating)>=58
                                    )
                AND STAR_RATING IN (
                                    SELECT star_rating
                                    FROM books
                                    GROUP BY product_id
                                    HAVING COUNT(star_rating)>32
                                    );
                ''', conn)

    df = df.reset_index(drop=True)
    return df

In [8]:
df = import_standard_data('/Users/Dustin/GT_project/test2.db')

In [9]:
df.head(10)

,customer_id,product_id,product_parent,star_rating,helpful_votes,review_headline,review_body,product_category,marketplace,review_date,verified_purchase
0,25933450,0439873800,84656342,5,0.0,Five Stars,I love it and so does my students!,Books,US,2015-08-31,Y
1,1801372,1623953553,729938122,5,0.0,"Please buy ""I Saw a Friend""! Your children wil...",My wife and I ordered 2 books and gave them as...,Books,US,2015-08-31,Y
2,5782091,142151981X,678139048,5,0.0,Shipped fast.,Great book just like all the others in the ser...,Books,US,2015-08-31,Y
3,32715830,014241543X,712432151,5,0.0,Five Stars,So beautiful,Books,US,2015-08-31,N
4,14005703,1604600527,800572372,5,2.0,Five Stars,Enjoyed the author's story and his quilts are ...,Books,US,2015-08-31,Y
5,44121167,1517007240,299984591,5,2.0,The Monastery Murders - Book 2: Devil in the D...,"&#34;Secrets in the Shallows,&#34; Book 1 of &...",Books,US,2015-08-31,N
6,16519255,0671728725,821650353,5,0.0,Five Stars,I love it!,Books,US,2015-08-31,Y
7,49361350,1111349533,419457767,5,0.0,Five Stars,It was a great purchase.,Books,US,2015-08-31,Y
8,11423253,812211637X,285887177,5,0.0,Five Stars,Quality product fast shipping.,Books,US,2015-08-31,Y
9,37536260,0679413359,58983679,5,0.0,Five Stars,Very happy,Books,US,2015-08-31,Y